CREATE TABLE IF NOT EXISTS Users (

    userId INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50),
    password_hash VARCHAR(200)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 
)

CREATE TABLE IF NOT EXISTS Contacts (

    id INT PRIMARY KEY,
    FOREIGN KEY (userId) REFERENCES Users(userId),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(60) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)